In [24]:
aList=[1,2,3,4]
it=iter(aList)
print(it)
print(type(it))

<class 'list_iterator'>


In [25]:
alist=[1,2,3,4]
it=iter(aList)
while True:
    try:
        num=next(it)
        print(num)
    except StopIteration:
        break

1
2
3
4


In [26]:
def squares(x):
    for i in range(x):
        # print(i*i)
        yield i*i
print(squares(5))
print(type(squares(5)))

<generator object squares at 0x70e3cd5ede00>
<class 'generator'>


In [27]:
def myDecorator(func):
    def wrapper():
        print("Before")
        func()
        print("After")
    return wrapper

In [28]:
@myDecorator
def sayHello():
    print("Hello")
# sayHello=myDecorator(sayHello)
# sayHelloo()

In [29]:
sayHello()

Before
Hello
After


In [30]:
import time
def timer(func):
    def wrapper(*args,**kwargs):
        start=time.time()
        result=func(*args,**kwargs)
        end=time.time()
        print(f"Elapsed time={end-start} seconds")
        return result
    return wrapper

In [31]:
@timer
def fact(n):
    f=1
    for i in range(1,n+1):
        f=f*i
    return f
fact(100)

Elapsed time=1.2874603271484375e-05 seconds


93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000

In [32]:
def squares(n=10):
    print(f'Genreating the squares from 1 to {n ** 2}')
    for i in range(1,n+1):
        yield i **2
gen=squares()
gen

<generator object squares at 0x70e3cd5ee260>

In [33]:
type(gen)

generator

In [34]:
for x in gen:
    print(x,end=' ')

Genreating the squares from 1 to 100
1 4 9 16 25 36 49 64 81 100 

In [35]:
import numpy as np
data=np.array([[1.5,-0.1,3],[0,-3,6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [36]:
data*10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [37]:
data+data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [38]:
import pandas as pd
obj=pd.Series([4,3,-5,2])
obj

0    4
1    3
2   -5
3    2
dtype: int64

In [39]:
obj.array

<NumpyExtensionArray>
[4, 3, -5, 2]
Length: 4, dtype: int64

In [40]:
obj.index

RangeIndex(start=0, stop=4, step=1)